### ISSUE TITLE
Requirements install error

### ISSUE THREAD

**Issue by littletigerwolf** [arenasys/Lineworks#1]
Mode: NVIDIA
Windows 10

Log:

GUI 2023-11-28 20:14:19.648283
Traceback (most recent call last):
  File "F:\Lineworks-master\source\main.py", line 225, in run
    raise RuntimeError("Failed to install: ", pkg, "\n", output)
RuntimeError: ('Failed to install: ', 'llama-cpp-python', '\n', 'ERROR: llama_cpp_python_cuda-0.2.11+cu121-cp311-cp311-win_amd64.whl is not a supported wheel on this platform.\n\n[notice] A new release of pip is available: 23.2.1 -> 23.3.1\n[notice] To update, run: pythonw.exe -m pip install --upgrade pip\n')

**Comment by arenasys** [comment]
https://github.com/arenasys/Lineworks/commit/7c3ba7c99d2d76cbfe0e0ac6e85e77702c2c0bb9 should fix it. delete and redownload.
