### ISSUE TITLE
No models in tab

### ISSUE THREAD

**Issue by littletigerwolf** [arenasys/Lineworks#2]
GUI do not see any models in folder

<details>
<summary>Screenshots</summary>

![изображение](https://github.com/arenasys/Lineworks/assets/16870344/08ca14da-3170-4139-9393-7f6463f4e293)
![изображение](https://github.com/arenasys/Lineworks/assets/16870344/1598e217-8f01-42cd-9a4c-8e39f759ebad)
<details>

**Comment by arenasys** [comment]
It will only find new models on startup. Im guessing you have tried restarting Lineworks?

**Comment by littletigerwolf** [comment]
> It will only find new models on startup. Im guessing you have tried restarting Lineworks?

Several times, as administrator too

**Comment by arenasys** [comment]
Added an error if it fails to find the model folder, will show where its looking for models.

**Comment by littletigerwolf** [comment]
> Added an error if it fails to find the model folder, will show where its looking for models.

After update via GUI (File->Update) i get this error on startup
Crash.log was not generated
<details>
<summary>Screenshot</summary>

![изображение](https://github.com/arenasys/Lineworks/assets/16870344/d1ca6150-df11-4482-a221-347eabd51f69)
<details>

**Comment by arenasys** [comment]
Ah, delete the `venv` folder and let it reinstall. You are using NVIDIA right? I'll improve that error anyway.

**Comment by littletigerwolf** [comment]
I take error again D: (i fully deleted folder and reinstall)

Yep, i using NVIDIA mode

<details>
<summary>Screenshot</summary>

![изображение](https://github.com/arenasys/Lineworks/assets/16870344/e74b4324-d79e-4388-baae-1c9fd280ae4a)
</details>

**Comment by arenasys** [comment]
Can you check to see if that `llama.dll` exists (it does in the wheel). Otherwise its missing something it was dynamically linked with:
```
    cudart64_12.dll
    cublas64_12.dll
    KERNEL32.dll
    MSVCP140.dll
    VCRUNTIME140.dll
    VCRUNTIME140_1.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-filesystem-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-convert-l1-1-0.dll
    api-ms-win-crt-time-l1-1-0.dll
    api-ms-win-crt-math-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-environment-l1-1-0.dll
```
So its linked against the Windows API + the Visual C++ Runtime (you probably have these). Then also the CUDA 12 DLLs.
Im guessing its an issue with the CUDA DLLs. What GPU do you have and whats the driver version?

**Comment by arenasys** [comment]
Seems I needed to provide those CUDA DLLs, added in https://github.com/arenasys/Lineworks/commit/3cce9e2687ff66b3ca3eade46b2172d45e364b5e. update and it should prompt you to install some nvidia packages.

**Comment by littletigerwolf** [comment]
Thanks for your work! =)
